### ISSUE TITLE
Modify source to hosting on localhost

### ISSUE THREAD

**Issue by digitalghost** [xxmichaellong/ptcg-sim#15]
兄弟，不知道你知否能看中文，我觉得应该是可以的。
现在有个问题，我为了能在本地运行，按照您的要求，修改了global-variables.js的第 5 行，将 socket修改为了localhost:4000,
同时因为我无法访问外网，所以只能被迫修改硬编码的卡背图片文件地址，指向本地的cardback.png,这个修改我是在global-variables.js的 41-43 行进行修改的，这 3 行的地址分别都改为了相同的/src/cardback.png文件。
同时修改了 50 行的preloadImage也变成了/src/cardback.png文件。

经过这样的修改过后，我发现一个问题，文件是不去外网请求了，但是当把选项Hide opponent's hand (1P mode)打开的时候，当旋转到对方视角的时候，会导致双方的牌都无法显示，只能显示cardback了，没去细看代码究竟为什么，是否可以教我解决下这个问题。

这个工具对于战队练习，效率非常高，比ptcg live游戏本身还好，希望能越做越好，加油～！

If you can not read chinese, plz reply ,I will translate my issus again.

**Comment by xxmichaellong** [comment]
Hi! I translated your response to English. The issue you are having is because you are using the relative URL instead of the absolute URL for the card backs. The hide/reveal card logic only works with absolute URLs. Please change your card back source to this and it should work:

![image](https://github.com/xxmichaellong/ptcg-sim/assets/132688898/43b89bb1-d0c0-46ef-b36a-461ef2a612d7)

By the way, why are you having issues requesting images from external networks? All of the images for the cards are sourced from external networks, so I would think the problem would apply to all cards, not just the card back. Are you sourcing all of your cards locally?

**Comment by digitalghost** [comment]
Hi,buddy:

the question you mentioned "By the way, why are you having issues requesting images from external networks?", the reason is for some reason  , my network could not access ptcgsim.online, but I can access other website such as the card image comes from.

I modified the file as your codes, the issues resolved, thank you vary much.
